FROM gcr.io/tfx-oss-public/tfx:1.15.1

COPY src/solutions/monitorer_component monitorer_component

RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install google-cloud-aiplatform==1.52.0

ENV PYTHONPATH="/tfx/src:${PYTHONPATH}"
