FROM europe-docker.pkg.dev/par-devfest-sfeir/eu.gcr.io/tfx_augm:1.9.1

ENV GOOGLE_CLOUD_PROJECT = 'par-devfest-sfeir'
ENV GOOGLE_CLOUD_REGION = 'europe-west1'
ENV GCS_BUCKET_NAME = 'devfest_mlops_2022'

RUN mkdir devfest_mlops

RUN pip install --upgrade pip
RUN pip install jupyter
RUN pip install --upgrade "tfx[kfp]<2"

EXPOSE 8888

ENTRYPOINT ["/bin/sh"]
