FROM gcr.io/tfx-oss-public/tfx:1.9.1

COPY src/solutions/monitorer_component monitorer_component

RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install google-cloud-aiplatform==1.17.1

ENV PYTHONPATH="/tfx/src:${PYTHONPATH}"
